using System;
using UnityEngine.SceneManagement;

namespace ScalingLaws.Core
{
    /// <summary>
    /// Scene names and the handful of flags that survive a scene load. Both scenes are generated by
    /// the editor builder, so these names are the contract between the builder and the runtime and
    /// must not drift apart.
    /// </summary>
    public static class SceneFlow
    {
        public const string MainMenuScene = "MainMenu";
        public const string GameScene = "Game";

        /// <summary>
        /// Set by the menu before loading the game scene. True resumes the stored campaign, false
        /// starts a fresh one. A static flag because it is the only thing that has to cross a scene
        /// boundary, and a whole persistent object for one boolean is not worth it.
        /// </summary>
        public static bool ResumeSavedCampaign { get; set; }

        /// <summary>Company name typed on the menu, used only when starting fresh.</summary>
        public static string RequestedCompanyName { get; set; } = "Prometheus AI";

        /// <summary>Which opening tile was chosen. Read once by the game scene.</summary>
        public static int RequestedArchetype { get; set; }

        /// <summary>The two founder traits picked, as enum values.</summary>
        public static int RequestedTraitA { get; set; }

        public static int RequestedTraitB { get; set; }

        /// <summary>What the founder is called. Carried into the campaign, never into the save key.</summary>
        public static string RequestedFounderName { get; set; } = "Anonymous";

        /// <summary>Skill levels chosen at creation, in catalog order. Empty means every default.</summary>
        public static int[] RequestedSkillLevels { get; set; } = Array.Empty<int>();

        /// <summary>Where the company registers. Zero means the default, America.</summary>
        public static int RequestedRegion { get; set; }

        /// <summary>The country inside that region. Zero means the region's first entry.</summary>
        public static int RequestedCountry { get; set; }

        /// <summary>Starts a campaign from the opening flow rather than from defaults.</summary>
        public static void StartNewCampaign(string companyName, int archetype, int traitA, int traitB)
        {
            RequestedArchetype = archetype;
            RequestedTraitA = traitA;
            RequestedTraitB = traitB;
            StartNewCampaign(companyName);
        }

        public static void LoadMainMenu()
        {
            SceneManager.LoadScene(MainMenuScene);
        }

        public static void StartNewCampaign(string companyName)
        {
            ResumeSavedCampaign = false;
            RequestedCompanyName = string.IsNullOrWhiteSpace(companyName) ? "Prometheus AI" : companyName.Trim();
            SceneManager.LoadScene(GameScene);
        }

        public static void ResumeCampaign()
        {
            ResumeSavedCampaign = true;
            SceneManager.LoadScene(GameScene);
        }
    }
}
