using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace ScalingLaws.Editor
{
    /// <summary>
    /// Lightens the house the campaign opens in: pale oak underfoot, plaster on the walls, brushed
    /// metal, and a reflection probe so the floor has something to reflect.
    ///
    /// **It repaints, it does not rebuild.** `OfficeRoomBuilder` writes `OfficeRoom.prefab` from
    /// scratch, and the house in `Game.unity` is an instance of that prefab carrying the author's
    /// own hand-placed furniture as overrides keyed by object id. Regenerating the prefab issues new
    /// ids, so every one of those overrides would snap back to where the generator puts things and a
    /// week of furnishing would be gone. Materials are separate assets with their own guids: editing
    /// one in place changes every surface using it, in the prefab and in the scene, and moves
    /// nothing.
    ///
    /// The textures are generated by <see cref="TextureForge"/>, the same stand-ins the rented
    /// floors use, so the house reads as the same world rather than as a different game.
    /// </summary>
    public static class HouseLook
    {
        private const string MaterialFolder = "Assets/_ScalingLaws/Materials";
        private const string PrefabPath = "Assets/_ScalingLaws/Prefabs/OfficeRoom.prefab";

        /// <summary>The floor is one surface, so one tiling figure is honest for the whole of it.</summary>
        private static readonly Vector2 FloorTiling = new(4f, 3f);

        private static readonly Vector2 WallTiling = new(3f, 1.5f);

        [MenuItem("Scaling Laws/Lighten the house")]
        public static void Run()
        {
            var floor = TextureForge.Planks("HouseOak", new Color(0.78f, 0.66f, 0.50f), 7);
            var plaster = TextureForge.Stone("HousePlaster", new Color(0.88f, 0.88f, 0.87f));

            // Pale oak, plaster, brushed aluminium, and the soft furnishings a lit room needs to not
            // read as a warehouse. Everything here was between a third and a half as bright.
            Paint("RoomConcrete", new Color(0.82f, 0.74f, 0.62f), 0.42f, 0.0f, floor, FloorTiling);
            Paint("RoomWallCool", new Color(0.87f, 0.88f, 0.90f), 0.10f, 0.0f, plaster, WallTiling);
            Paint("RoomWallWarm", new Color(0.92f, 0.88f, 0.82f), 0.10f, 0.0f, plaster, WallTiling);
            Paint("RoomTimber", new Color(0.76f, 0.61f, 0.42f), 0.28f);
            Paint("RoomTimberDark", new Color(0.58f, 0.45f, 0.33f), 0.24f);
            Paint("RoomMetal", new Color(0.70f, 0.72f, 0.76f), 0.58f, 0.65f);
            Paint("RoomFabric", new Color(0.80f, 0.79f, 0.76f), 0.12f);
            Paint("RoomSofa", new Color(0.55f, 0.63f, 0.53f), 0.12f);
            Paint("RoomBedding", new Color(0.64f, 0.72f, 0.84f), 0.12f);
            Paint("RoomLinen", new Color(0.93f, 0.93f, 0.91f), 0.14f);
            Paint("RoomCardboard", new Color(0.80f, 0.68f, 0.50f), 0.10f);
            Paint("RoomTerracotta", new Color(0.74f, 0.47f, 0.34f), 0.16f);
            Paint("RoomFoliage", new Color(0.34f, 0.55f, 0.32f), 0.16f);
            Paint("RoomAccent", new Color(0.72f, 0.33f, 0.30f), 0.18f);

            // The one light source inside the room's own geometry. Emissive rather than bright, so it
            // reads as a lamp that is on rather than as a white box.
            Paint("RoomLamp", new Color(0.98f, 0.90f, 0.72f), 0.20f, 0.0f, null, null,
                new Color(1.0f, 0.86f, 0.62f) * 1.6f);

            AddReflections();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log("HOUSE: repainted 15 materials and set the reflection probe. "
                + "Geometry and every hand-placed piece untouched.");
        }

        /// <summary>
        /// Edits one material asset in place, keeping its guid so nothing that references it moves.
        /// </summary>
        private static void Paint(string name, Color colour, float smoothness, float metallic = 0f,
            Texture2D texture = null, Vector2? tiling = null, Color? emission = null)
        {
            var path = $"{MaterialFolder}/{name}.mat";
            var material = AssetDatabase.LoadAssetAtPath<Material>(path);

            if (material == null)
            {
                Debug.LogWarning($"HOUSE: {path} is not there, so nothing was repainted for {name}.");
                return;
            }

            material.color = colour;

            if (material.HasProperty("_BaseColor"))
            {
                material.SetColor("_BaseColor", colour);
            }

            // Built-in calls it glossiness and URP calls it smoothness. Both are written where they
            // exist rather than guessing which pipeline is on, the way the room builders already do.
            if (material.HasProperty("_Smoothness"))
            {
                material.SetFloat("_Smoothness", smoothness);
            }

            if (material.HasProperty("_Glossiness"))
            {
                material.SetFloat("_Glossiness", smoothness);
            }

            if (material.HasProperty("_Metallic"))
            {
                material.SetFloat("_Metallic", metallic);
            }

            material.mainTexture = texture;
            material.mainTextureScale = tiling ?? Vector2.one;

            if (emission.HasValue)
            {
                material.EnableKeyword("_EMISSION");
                material.SetColor("_EmissionColor", emission.Value);
                material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
            }
            else
            {
                material.DisableKeyword("_EMISSION");
                material.SetColor("_EmissionColor", Color.black);
            }

            EditorUtility.SetDirty(material);
        }

        /// <summary>
        /// Puts one box-projected reflection probe in the middle of the house, or moves the one that
        /// is already there.
        ///
        /// **Added to the prefab rather than regenerated with it**, through
        /// <see cref="PrefabUtility.LoadPrefabContents"/>: adding a child leaves every existing
        /// object id alone, so the scene's overrides survive and the probe appears in the house that
        /// is already furnished.
        ///
        /// Realtime and refreshed once on awake rather than a cubemap written to disk, because the
        /// house is lit by lamps the player upgrades and a picture taken today would be of a room
        /// that no longer exists. One render at load is cheap; a probe that never refreshes is a
        /// mirror of nothing.
        /// </summary>
        private static void AddReflections()
        {
            if (!File.Exists(PrefabPath))
            {
                Debug.LogWarning($"HOUSE: {PrefabPath} is not there, so no probe was set.");
                return;
            }

            var contents = PrefabUtility.LoadPrefabContents(PrefabPath);

            try
            {
                var existing = contents.transform.Find("Reflections");
                var probeObject = existing != null
                    ? existing.gameObject
                    : new GameObject("Reflections");

                if (existing == null)
                {
                    probeObject.transform.SetParent(contents.transform, false);
                }

                probeObject.transform.localPosition = new Vector3(6.0f, 1.4f, 4.5f);

                // **`??` is the wrong operator on a Unity component.** A missing component comes
                // back as an object that only compares equal to null through Unity's own operator,
                // so the coalesce keeps the empty one and the first property set throws.
                var probe = probeObject.GetComponent<ReflectionProbe>();
                if (probe == null)
                {
                    probe = probeObject.AddComponent<ReflectionProbe>();
                }

                probe.mode = UnityEngine.Rendering.ReflectionProbeMode.Realtime;
                probe.refreshMode = UnityEngine.Rendering.ReflectionProbeRefreshMode.OnAwake;
                probe.timeSlicingMode = UnityEngine.Rendering.ReflectionProbeTimeSlicingMode.AllFacesAtOnce;
                probe.boxProjection = true;
                probe.size = new Vector3(12.4f, 6.4f, 9.4f);
                probe.center = Vector3.zero;
                probe.intensity = 1f;
                probe.importance = 2;
                probe.resolution = 128;
                probe.cullingMask = ~0;
                probe.clearFlags = UnityEngine.Rendering.ReflectionProbeClearFlags.SolidColor;
                probe.backgroundColor = new Color(0.16f, 0.17f, 0.20f);

                PrefabUtility.SaveAsPrefabAsset(contents, PrefabPath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(contents);
            }
        }
    }
}
